# Generated by Django 5.2.1 on 2025-06-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pagecategory_alter_page_options_page_show_in_toc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('tech', models.BooleanField(default=False, help_text='Subscribe to Technology blog posts')),
                ('life', models.BooleanField(default=False, help_text='Subscribe to Life Management blog posts')),
                ('spirit', models.BooleanField(default=False, help_text='Subscribe to Spiritual Growth blog posts')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is active')),
                ('confirmation_token', models.CharField(blank=True, help_text='Token for email confirmation', max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When email was confirmed', null=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
