# Generated by Django 5.2.1 on 2025-06-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload banner image', null=True, upload_to='pages/banners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload featured image', null=True, upload_to='pages/featured/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload banner image', null=True, upload_to='posts/banners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_upload',
            field=models.ImageField(blank=True, help_text='Upload featured image (recommended)', null=True, upload_to='posts/featured/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Upload thumbnail image', null=True, upload_to='posts/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.URLField(blank=True, help_text='URL to featured image (legacy)'),
        ),
    ]
